### ISSUE TITLE
Meeting (10/02/2022)

### ISSUE THREAD

**Issue by misterhtmlcss** [misterhtmlcss/df-mastermind#2]
1. Post your update ex.
- What have you been working on?
- Goals between now and next meeting?
- Where are you stuck (optional)? **Suggestions: Can be technical? Can be about time management? Depression, etc. Think broadly what's inhibiting you.

2. If you are stuck and there is some need for greater detail; this happens. For example you may need help with something to do with CSS Grid and it's just making something align differently. You can see that's easy enough to describe, but what if it's something difficult like Mobx + Angular 1.x something it's hard to explain. Then just give a headline here, then open a new Issue on here and explain in detail. Screenshots, etc can all be included there.

**Comment by misterhtmlcss** [comment]
- What have I been working on?
Rails contract is going well. Learning lots and it should help me with my pairing and my own coding.

- Goal from last meeting achieved? Not achieved? Next meeting?
Trying to get through chapter 4 of Poodr and I'm about 6 pages away from finishing it. It's really interesting stuff.
For next week it's to get back on track and finish Week 2.
Pair more. I did twice this week and looking to do 3 or more next week.

- Where are you stuck?
Mentally struggling to move forward on IS work.

**Comment by MKCMMSK** [comment]
- What have I been working on?
  Interview prep, some IS work, prepping for a contract

- Goal from last meeting achieved? Not achieved? Next meeting?
  I don't quite remember what goals were set from last week, but I'd imagine I didn't hit them.
  For next meeting though, I'm hoping to be on week 4 of IS along with having my contract ironed out and be less iffy about certain aspects of it.

- Where are you stuck?
  Generally life things, recent week was hectic due to that. No excuse to fall behind goals and career though. Working through it.
  Potentially some front end web3 work if anyone is familiar with that.

**Comment by rhurtis** [comment]
- What have you been working on?
Tying up loose ends at work for the final week. Learning/coding for my next position. Imposter school tasks.

- Goal from last meeting achieved?
My goal from the last meeting was to finish week3 content and I did not achieve it.

- Goals between now and next meeting?
My goal between now and the next meeting is to finish week 4 content. 

- Where are you stuck (optional)? 
I am stuck because my time and energy are being taken up by other activities (mostly work). However, this is going to change next week.

**Comment by JakeFantin** [comment]
- What have you been working on?
Finding a place to live.  Side job tasks.

- Goal from last meeting achieved?
No, I believe the goal was ten showings, I have booked 4 and been to 1. Better than nothing!

- Goals between now and next meeting?
Four more viewings. End of Week 2 content.

**Comment by misterhtmlcss** [comment]
@JakeFantin @MKCMMSK @rhurtis see you all on Sunday. Commitment was to try to get to W3 and from there we mob program together.

Mob programming...what is it: https://www.youtube.com/watch?v=jhImlR4_Vto
Live Demo of Mob programming: https://www.youtube.com/watch?v=JeLKTvkGLN

Opportunities with great tech companies that have Mob and Pair programming as part of their ethos.
<img width="637" alt="Screen Shot 2022-02-11 at 8 41 47 AM" src="https://user-images.githubusercontent.com/13112566/153622072-ce007f7e-c9e6-4a09-8ff4-eac1de8175a2.png">
Q
